version: '3'
services:
  store:
    image: store:latest
    container_name: store
    env_file: .env
    build:
      context: .
      dockerfile: ./Dockerfile.local
      args:
        - PUBLIC_ASSETS_PATH
    ports:
      - 5173:5173
    volumes:
      - ./:/src/store
    command: npm run dev:with-codegen -- --host
    security_opt:
      - no-new-privileges:true
    read_only: true
    depends_on:
      api:
        condition: service_started
  api:
    image: api:latest
    container_name: api
    env_file: ./api/.env
    environment:
      - DB_URL=user:password@postgres
    build:
      context: ./api
      args:
        - SESSION_SECRET
    ports:
      - 3000:3000
    volumes:
      - ./api:/src/api
    command: npm run dev
    security_opt:
      - no-new-privileges:true
    read_only: true
    depends_on:
      - postgres
  postgres:
    image: postgres:14
    restart: always
    container_name: postgres
    environment:
        - POSTGRES_USER=user
        - POSTGRES_PASSWORD=password
    ports:
      - 5432:5432
    volumes: 
      - db:/var/lib/postgresql/data
    security_opt:
      - no-new-privileges:true
    read_only: true
volumes:
  db:
    driver: local