FROM public.ecr.aws/docker/library/node:18

WORKDIR /app

COPY ["package.json", "package-lock.json*", "./"]

RUN npm ci --ignore-scripts

COPY . .

ARG PUBLIC_ASSETS_PATH

RUN npm ci

RUN npm run build

CMD [ "npm", "run", "start" ]
