minimumReleaseAge: 10080 # minutes; 7 days = 10080

blockExoticSubdeps: true

trustPolicy: "no-downgrade"
trustPolicyIgnoreAfter: 43200 # minutes; 30 days

allowBuilds:
  "@brave/leo": true
  '@parcel/watcher': false
  esbuild: false
  svelte-preprocess: false

publicHoistPattern:
  - "graphql-tag"

overrides:
  brace-expansion@>=4.0.0 <5.0.9: ^5.0.9
  cookie: 1.0.2

verifyDepsBeforeRun: install

engineStrict: true

minimumReleaseAgeExclude:
  - brace-expansion@5.0.9
